name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Install components
      run: | 
        rustup toolchain install nightly
        rustup component add llvm-tools-preview
        rustup component add rust-src
    - name: Install build tools
      run: |
        cargo install cargo-xbuild
        cargo install bootimage --version "^0.7.7"
    - name: Build
      run: cargo bootimage --verbose
    - name: Run tests
      run: cargo test --verbose
      
