name: Glass OS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Install components
      run: | 
        rustup toolchain install nightly
        rustup component add llvm-tools-preview
        rustup component add rust-src
    - name: Install build tools
      run: |
        cargo install cargo-binutils
        cargo install cargo-xbuild
        cargo install bootimage --version "^0.7.7"
    - name: Build
      run: cargo bootimage --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: glass-os
        path: 'target/**/*.bin'
      
